# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/mustafa/E/College/2nd_Term/AI/Project/Othello-Game/src/gui/forms/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(223,223,223);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("QWidget#main_menu_page{\n"
"    border-image: url(:imgs/imgs/othello_bg_half_trans.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_menu_page = QtWidgets.QWidget()
        self.main_menu_page.setStyleSheet("/*PushButton*/\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(223, 223, 223);\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"")
        self.main_menu_page.setObjectName("main_menu_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_menu_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_page_frame = QtWidgets.QFrame(self.main_menu_page)
        self.main_page_frame.setStyleSheet("")
        self.main_page_frame.setObjectName("main_page_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_page_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_menu_start_btn = QtWidgets.QPushButton(self.main_page_frame)
        self.main_menu_start_btn.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.main_menu_start_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/start_game_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_menu_start_btn.setIcon(icon)
        self.main_menu_start_btn.setIconSize(QtCore.QSize(28, 28))
        self.main_menu_start_btn.setObjectName("main_menu_start_btn")
        self.verticalLayout_3.addWidget(self.main_menu_start_btn)
        self.main_menu_options_btn = QtWidgets.QPushButton(self.main_page_frame)
        self.main_menu_options_btn.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.main_menu_options_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/settings_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_menu_options_btn.setIcon(icon1)
        self.main_menu_options_btn.setIconSize(QtCore.QSize(28, 28))
        self.main_menu_options_btn.setObjectName("main_menu_options_btn")
        self.verticalLayout_3.addWidget(self.main_menu_options_btn)
        self.main_menu_quit_btn = QtWidgets.QPushButton(self.main_page_frame)
        self.main_menu_quit_btn.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.main_menu_quit_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/quit_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_menu_quit_btn.setIcon(icon2)
        self.main_menu_quit_btn.setIconSize(QtCore.QSize(28, 28))
        self.main_menu_quit_btn.setObjectName("main_menu_quit_btn")
        self.verticalLayout_3.addWidget(self.main_menu_quit_btn)
        self.verticalLayout_2.addWidget(self.main_page_frame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.main_menu_page)
        self.game_page = QtWidgets.QWidget()
        self.game_page.setStyleSheet("/*PushButton*/\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(223, 223, 223);\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QWidget#game_page{\n"
"    background-color: rgb(44, 49, 59);\n"
"}\n"
"/*Frame*/\n"
"QFrame{\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"")
        self.game_page.setObjectName("game_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.game_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu_container_widget = QtWidgets.QWidget(self.game_page)
        self.side_menu_container_widget.setObjectName("side_menu_container_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.side_menu_container_widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.side_menu_frame = QtWidgets.QFrame(self.side_menu_container_widget)
        self.side_menu_frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        self.side_menu_frame.setFont(font)
        self.side_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_frame.setObjectName("side_menu_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.side_menu_frame)
        self.verticalLayout_7.setSpacing(14)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.side_menu_toggle = QtWidgets.QPushButton(self.side_menu_frame)
        self.side_menu_toggle.setMinimumSize(QtCore.QSize(50, 50))
        self.side_menu_toggle.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.side_menu_toggle.setFont(font)
        self.side_menu_toggle.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/dots_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.side_menu_toggle.setIcon(icon3)
        self.side_menu_toggle.setIconSize(QtCore.QSize(28, 28))
        self.side_menu_toggle.setObjectName("side_menu_toggle")
        self.verticalLayout_7.addWidget(self.side_menu_toggle)
        self.side_menu_sound_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.side_menu_sound_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.side_menu_sound_btn.setFont(font)
        self.side_menu_sound_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/volume_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.side_menu_sound_btn.setIcon(icon4)
        self.side_menu_sound_btn.setIconSize(QtCore.QSize(28, 28))
        self.side_menu_sound_btn.setObjectName("side_menu_sound_btn")
        self.verticalLayout_7.addWidget(self.side_menu_sound_btn)
        self.side_menu_back_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.side_menu_back_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.side_menu_back_btn.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.side_menu_back_btn.setFont(font)
        self.side_menu_back_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/arrow_back_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.side_menu_back_btn.setIcon(icon5)
        self.side_menu_back_btn.setIconSize(QtCore.QSize(28, 28))
        self.side_menu_back_btn.setObjectName("side_menu_back_btn")
        self.verticalLayout_7.addWidget(self.side_menu_back_btn, 0, QtCore.Qt.AlignTop)
        self.side_menu_restart_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.side_menu_restart_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.side_menu_restart_btn.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.side_menu_restart_btn.setFont(font)
        self.side_menu_restart_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/restart_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.side_menu_restart_btn.setIcon(icon6)
        self.side_menu_restart_btn.setIconSize(QtCore.QSize(28, 28))
        self.side_menu_restart_btn.setObjectName("side_menu_restart_btn")
        self.verticalLayout_7.addWidget(self.side_menu_restart_btn, 0, QtCore.Qt.AlignTop)
        self.side_menu_quit_btn = QtWidgets.QPushButton(self.side_menu_frame)
        self.side_menu_quit_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.side_menu_quit_btn.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setBold(True)
        self.side_menu_quit_btn.setFont(font)
        self.side_menu_quit_btn.setText("")
        self.side_menu_quit_btn.setIcon(icon2)
        self.side_menu_quit_btn.setIconSize(QtCore.QSize(28, 28))
        self.side_menu_quit_btn.setObjectName("side_menu_quit_btn")
        self.verticalLayout_7.addWidget(self.side_menu_quit_btn, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.side_menu_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 455, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.side_menu_container_widget, 0, QtCore.Qt.AlignLeft)
        self.game_content_container_widget = QtWidgets.QWidget(self.game_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_content_container_widget.sizePolicy().hasHeightForWidth())
        self.game_content_container_widget.setSizePolicy(sizePolicy)
        self.game_content_container_widget.setObjectName("game_content_container_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.game_content_container_widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.game_info_frame = QtWidgets.QFrame(self.game_content_container_widget)
        self.game_info_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.game_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.game_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.game_info_frame.setObjectName("game_info_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.game_info_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.game_info_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.turn_label = QtWidgets.QLabel(self.game_info_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        self.turn_label.setFont(font)
        self.turn_label.setObjectName("turn_label")
        self.horizontalLayout_6.addWidget(self.turn_label)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.game_info_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.white_score_label = QtWidgets.QLabel(self.game_info_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        self.white_score_label.setFont(font)
        self.white_score_label.setObjectName("white_score_label")
        self.horizontalLayout_5.addWidget(self.white_score_label)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.game_info_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.black_score_label = QtWidgets.QLabel(self.game_info_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        self.black_score_label.setFont(font)
        self.black_score_label.setObjectName("black_score_label")
        self.horizontalLayout_4.addWidget(self.black_score_label)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_8.addWidget(self.game_info_frame)
        self.board_frame = QtWidgets.QFrame(self.game_content_container_widget)
        self.board_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.board_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.board_frame.setObjectName("board_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.board_frame)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, 11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.board_table_widget = QtWidgets.QTableWidget(self.board_frame)
        self.board_table_widget.setMaximumSize(QtCore.QSize(665, 16777215))
        self.board_table_widget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(4, 135, 69);\n"
"    color: rgb(223, 223, 223);\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    padding: 10px;\n"
"    gridline-color: rgb(44, 100, 59);\n"
"}\n"
"\n"
"QTableWidget::item:selected{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"")
        self.board_table_widget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.board_table_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.board_table_widget.setObjectName("board_table_widget")
        self.board_table_widget.setColumnCount(8)
        self.board_table_widget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.board_table_widget.setHorizontalHeaderItem(7, item)
        self.board_table_widget.horizontalHeader().setVisible(False)
        self.board_table_widget.horizontalHeader().setDefaultSectionSize(80)
        self.board_table_widget.horizontalHeader().setMinimumSectionSize(80)
        self.board_table_widget.verticalHeader().setVisible(False)
        self.board_table_widget.verticalHeader().setDefaultSectionSize(70)
        self.board_table_widget.verticalHeader().setMinimumSectionSize(70)
        self.horizontalLayout_3.addWidget(self.board_table_widget)
        self.verticalLayout_8.addWidget(self.board_frame)
        self.horizontalLayout.addWidget(self.game_content_container_widget)
        self.stackedWidget.addWidget(self.game_page)
        self.options_page = QtWidgets.QWidget()
        self.options_page.setStyleSheet("/*PushButton*/\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(223, 223, 223);\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"/*Frame*/\n"
"QFrame{\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"QWidget#options_page{\n"
"    background-color: rgb(44, 49, 59);\n"
"}")
        self.options_page.setObjectName("options_page")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.options_page)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.widget = QtWidgets.QWidget(self.options_page)
        self.widget.setStyleSheet("QGroupBox::title{\n"
"    color: rgb(223, 223, 223);\n"
"    top:-9px;\n"
"}\n"
"QGroupBox{\n"
"        margin-top:6px; \n"
"        padding-top: 10px;\n"
"        background-color: transparent;\n"
"        border-top: 2px solid white;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_7 = QtWidgets.QFrame(self.widget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.players_group_box = QtWidgets.QGroupBox(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.players_group_box.setFont(font)
        self.players_group_box.setFlat(False)
        self.players_group_box.setObjectName("players_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.players_group_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.players_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.ai_ai_option = AnimatedRadioButton(self.players_group_box)
        self.ai_ai_option.setText("")
        self.ai_ai_option.setObjectName("ai_ai_option")
        self.horizontalLayout_7.addWidget(self.ai_ai_option)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.players_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.human_ai_option = AnimatedRadioButton(self.players_group_box)
        self.human_ai_option.setText("")
        self.human_ai_option.setChecked(True)
        self.human_ai_option.setObjectName("human_ai_option")
        self.horizontalLayout_8.addWidget(self.human_ai_option)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.players_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.human_human_option = AnimatedRadioButton(self.players_group_box)
        self.human_human_option.setText("")
        self.human_human_option.setObjectName("human_human_option")
        self.horizontalLayout_9.addWidget(self.human_human_option)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_30.addWidget(self.players_group_box)
        self.horizontalLayout_15.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.widget)
        self.frame_8.setEnabled(True)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.black_difficulty_group_box = QtWidgets.QGroupBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.black_difficulty_group_box.setFont(font)
        self.black_difficulty_group_box.setFlat(False)
        self.black_difficulty_group_box.setObjectName("black_difficulty_group_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.black_difficulty_group_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.black_difficulty_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.easy_option = AnimatedRadioButton(self.black_difficulty_group_box)
        self.easy_option.setText("")
        self.easy_option.setChecked(True)
        self.easy_option.setObjectName("easy_option")
        self.horizontalLayout_10.addWidget(self.easy_option)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.black_difficulty_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.medium_option = AnimatedRadioButton(self.black_difficulty_group_box)
        self.medium_option.setText("")
        self.medium_option.setObjectName("medium_option")
        self.horizontalLayout_11.addWidget(self.medium_option)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.black_difficulty_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.hard_option = AnimatedRadioButton(self.black_difficulty_group_box)
        self.hard_option.setText("")
        self.hard_option.setObjectName("hard_option")
        self.horizontalLayout_12.addWidget(self.hard_option)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_32.addWidget(self.black_difficulty_group_box)
        self.horizontalLayout_15.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.widget)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.white_difficulty_group_box = QtWidgets.QGroupBox(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.white_difficulty_group_box.setFont(font)
        self.white_difficulty_group_box.setFlat(False)
        self.white_difficulty_group_box.setObjectName("white_difficulty_group_box")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.white_difficulty_group_box)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.white_difficulty_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.easy_option_2 = AnimatedRadioButton(self.white_difficulty_group_box)
        self.easy_option_2.setText("")
        self.easy_option_2.setChecked(True)
        self.easy_option_2.setObjectName("easy_option_2")
        self.horizontalLayout_13.addWidget(self.easy_option_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.white_difficulty_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.medium_option_2 = AnimatedRadioButton(self.white_difficulty_group_box)
        self.medium_option_2.setText("")
        self.medium_option_2.setObjectName("medium_option_2")
        self.horizontalLayout_14.addWidget(self.medium_option_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.white_difficulty_group_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.hard_option_2 = AnimatedRadioButton(self.white_difficulty_group_box)
        self.hard_option_2.setText("")
        self.hard_option_2.setObjectName("hard_option_2")
        self.horizontalLayout_16.addWidget(self.hard_option_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.verticalLayout_34.addWidget(self.white_difficulty_group_box)
        self.horizontalLayout_15.addWidget(self.frame_9)
        self.verticalLayout_36.addWidget(self.widget)
        self.frame_10 = QtWidgets.QFrame(self.options_page)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.optionButton = QtWidgets.QPushButton(self.frame_10)
        self.optionButton.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.optionButton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/done_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optionButton.setIcon(icon7)
        self.optionButton.setIconSize(QtCore.QSize(28, 28))
        self.optionButton.setObjectName("optionButton")
        self.horizontalLayout_17.addWidget(self.optionButton)
        self.default_options_btn = QtWidgets.QPushButton(self.frame_10)
        self.default_options_btn.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.default_options_btn.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons48x48/icons/48x48/restore_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.default_options_btn.setIcon(icon8)
        self.default_options_btn.setIconSize(QtCore.QSize(28, 28))
        self.default_options_btn.setObjectName("default_options_btn")
        self.horizontalLayout_17.addWidget(self.default_options_btn)
        self.back_options_btn = QtWidgets.QPushButton(self.frame_10)
        self.back_options_btn.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.back_options_btn.setFont(font)
        self.back_options_btn.setIcon(icon5)
        self.back_options_btn.setIconSize(QtCore.QSize(28, 28))
        self.back_options_btn.setObjectName("back_options_btn")
        self.horizontalLayout_17.addWidget(self.back_options_btn)
        self.verticalLayout_36.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.options_page)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_menu_start_btn.setText(_translate("MainWindow", "   START   "))
        self.main_menu_options_btn.setText(_translate("MainWindow", "  OPTIONS"))
        self.main_menu_quit_btn.setText(_translate("MainWindow", "    QUIT     "))
        self.label_9.setText(_translate("MainWindow", "Turn :"))
        self.turn_label.setText(_translate("MainWindow", "Black"))
        self.label_7.setText(_translate("MainWindow", "White :"))
        self.white_score_label.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Black :"))
        self.black_score_label.setText(_translate("MainWindow", "0"))
        item = self.board_table_widget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.board_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.board_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.board_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.board_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.board_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.board_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.board_table_widget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.board_table_widget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Column"))
        self.players_group_box.setTitle(_translate("MainWindow", "Game Mode"))
        self.label.setText(_translate("MainWindow", "AI vs AI"))
        self.label_2.setText(_translate("MainWindow", "Human vs AI"))
        self.label_3.setText(_translate("MainWindow", "Human vs Human"))
        self.black_difficulty_group_box.setTitle(_translate("MainWindow", "Black AI Difficulty level"))
        self.label_4.setText(_translate("MainWindow", "Easy"))
        self.label_6.setText(_translate("MainWindow", "Medium"))
        self.label_8.setText(_translate("MainWindow", "Hard"))
        self.white_difficulty_group_box.setTitle(_translate("MainWindow", "White AI Difficulty level "))
        self.label_10.setText(_translate("MainWindow", "Easy"))
        self.label_11.setText(_translate("MainWindow", "Medium"))
        self.label_12.setText(_translate("MainWindow", "Hard"))
        self.optionButton.setText(_translate("MainWindow", "  DONE"))
        self.default_options_btn.setText(_translate("MainWindow", "  RESTORE DEFAULT"))
        self.back_options_btn.setText(_translate("MainWindow", "  BACK"))
from headers.animatedradiobutton import AnimatedRadioButton
import resources_rc
